dist: trusty
language: ruby
sudo: required
bundler_args: "--jobs 3 --retry 3 --without nothing"
addons:
  chrome: stable
  hosts:
  - bridgembed
  code_climate:
    repo_token:
      secure: "B9QCgMoaDn0mvbun3Gk5GJBtvec4h50p5tbl1S8miqkkhOQkyJXBN0I5n0JzSNUcOqz/5K/sJSnDLqXWZ3QwyDKWD6Sv69/AiUZyui9nIBLxCQjUbs19Y6KKHflqMuRIYKetPkvzOeZUd9uMoKEr9l40qp58gwWT88qJfehNjMH6nMP378hNHtVl1iKb3Ey5jpmPH2nP3XLhoHEgymtJJ/nJGPfPQ54/jCuvu2ndZMmTxBg0mNY9rgnzYDtLM5ll6SH0Bvo6yscMCUxsBNKKtExz1/7BuEE8d12+CgTxWnIW0G6qdUsDG3ItbNUiz5vr7pGifUc3AKeME/vwTjvVov924EMfffBVZKFODYh4fV/FpXqmTQ50Wubq0LtIMENpA75jwGGtZQIHqBdICgVr1jJ37DljOnyyb2MU140ucEOx8465zCzB5JIeUTSM/hf4zx+dNQoJhY8H+RmXRrjAIqS5kOcnHky4y2D8I5bnVBuJ/DLu2RLRUWGXMrZmpzugBqsXu96keJUdtV/E1WC44mJi75aH8e5BRsLku4Pm7lC+tF0uJ/zw+HSU/2z7v7858nvlnp/cOrnAgXqD+VZ/ZfCqYpaXcetK4OfFOkYF1j958JhacnbB001Pa1O7HACHSIFeoVrSfyQMy3UtTQJAYl3kANQGc3UQwRiAm++VBzc="
before_install:
- sudo apt-get update
- sudo apt-get install tidy libicu52 redis-server
- redis-server &
- export NODE_PATH=$PWD/node_modules:$NODE_PATH
- curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash - && sudo apt-get install
  -y nodejs && npm install chrome-remote-interface minimist
- git clone https://${TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
- rm -rf config/projects && mkdir config/projects
- d=configurator/bridge/travis/bridge-reader/; for f in $(find $d -type f); do mkdir
  -p $(dirname "${f/$d/}"); cp "$f" "${f/$d/}"; done
- git clone https://github.com/meedan/pender.git
- d=configurator/bridge/travis/pender/; for f in $(find $d -type f); do cp "$f" "pender/${f/$d/}";
  done
- cd pender
- export BUNDLE_GEMFILE="$PWD/Gemfile"
- bundle install
- bundle exec rake db:migrate
- bundle exec sidekiq -L /tmp/sidekiq-log.log -d
- bundle exec rails runner 'a = ApiKey.create!; a.access_token = "test"; a.application_settings
  = { :webhook_url => "https://webhook.site/a459ece9-fe38-40b3-a522-54927de00e0e",
  :webhook_token => "x" }; a.save!'
- bundle exec rails s -p 3005 >/dev/null &
- cd -
before_script:
- export BUNDLE_GEMFILE="$PWD/Gemfile"
- bundle install
- RAILS_ENV=test bundle exec rake db:migrate
- RAILS_ENV=development bundle exec rake db:migrate
- bundle exec rails s -p 3002 >/dev/null &
- rm -f tmp/pids/server.pid
script: bundle exec rake test TESTOPTS="-v"
rvm:
- 2.3.1
notifications:
  slack:
    secure: V/0383FCUJ+GULRu2vPdE7fWILtbC7TW4aFAYR3R0Cmmc/bWMxmxTR4euHbzM0bhI0AmqwTCuGelNncCZNbQvH8Pa9UgDz4r1u1rXARlISwOhyxkHNGZHYZMHMbb4V+usO9G54MEyWaiL/CJ3ppOHXw3rmLSARn7/i0Y5FicIqYoU4Xk4GLsqT9K9/obLqid9AaCcgpzbSK6WfORjhSmVzoFSLY54YerVieWqJKXmIR4U6oToNq1xJ7qd8XfArJmJM21BXh6fJsgz6zhNd+fjto1p9emLSi/CBN8HYrt6gGkguwS12Yl/FXUWJ9IHLhEvzkNXfj+PSV/53KJJsoK5UfmrfOTl01OTWYsLt/o8qbd61uH6kOSEb5W5tJT4jIpX6FZL/gHombYNTzgy6JqB/0FuJ/4ZopoUFb/jVh4NomKu5TqV3cS+vx7cU4DOx81QFegg3k6ijjxgxwl+fTFJs1QsnfCveeOoNCeXcBpj6pqcZ7YSIaieywLr0zZuz3b29WT7yYrzbjolE5zMnmm88bvphmsDsT58GnxJYCU2iqCn/NlfVgj6W2ciKgihclA17vtjGXbboNyALAyZwvdsZagi8LxUAbnOLXAuFlxASk/stwjcE3SUl9YNr/DQneJqVs635UqN9PrvecqWCpy1UC8s82/cBytXN9ebLYjLXg=
env:
  global:
    secure: mP1qPT8gcwEXNLUCiBzKornU1CRFwcwBROqqoNDd89GHhgYP6en6fDnxDp6EFoAgA/YifcmagqvW7FCvHki017x++qHlxuSaMF26gVQbUyo7g3dIYbaJIHEMKV0s31AJqPbBQKftYAw+6A5TuCffcT1OEPm1x9ZzKVvRFNmc0Kj01xiEZrfqQXRKp5GbMe55ZYJV7uCwMvlhe3qzfgUxXr2Th6aaS4hXgXa8PbuUE/XFVVjHmnnSeZTsh5Jp9x181WLegAC9IhqzLxLafROLom5oxWFKgLIF75D79+O5Lu1dqfpZ2/4QLmY+2Hfb/k5SV+kQcx8yRbXiMAyVu2cOzi7N7Gyt4lyp30fdoBt2/wEARZYh5oNYd7HlSgiBia50ZwdkgpGGgbWfA6y4Xh0U0GpJe+kW6++41GbxFDjk0SLB/qYawC9xxdyrnhyBuMdFSrHxrckzdtXp7BAkHSwYYVnG/7QF+RMv8icM8oHCQc653iaFxvOeReZjLO3yw/Pyf2odMV0fi5abFBtOO3gC9TShyNisWevOuJoi/ezrPRFXDhMm+fJqXknSrdz+ye7k/CyWRYLXH6GCfMKvGSOippu5GDD8YKpnhNhDS9y49+DMzXgHP3Ozy8VWviYP9CEWG8IWKdw1H1hypnQxdaapNsd+SFAFTKiZ4nsGMOkiTkg=
